USE ecommerce_analytics;
SET FOREIGN_KEY_CHECKS=0;
DROP TABLE IF EXISTS user_events; DROP TABLE IF EXISTS payments; DROP TABLE IF EXISTS order_items; DROP TABLE IF EXISTS orders; DROP TABLE IF EXISTS products; DROP TABLE IF EXISTS users;
SET FOREIGN_KEY_CHECKS=1;
CREATE TABLE users (user_id BIGINT PRIMARY KEY, signup_date DATE NOT NULL, channel ENUM('organic','search','social','referral','display','affiliate') NOT NULL, region VARCHAR(20) NOT NULL, device ENUM('Android','iOS','Web') NOT NULL, age_group VARCHAR(10) NOT NULL);
CREATE TABLE products (product_id BIGINT PRIMARY KEY, category VARCHAR(30) NOT NULL, brand VARCHAR(40) NOT NULL, price DECIMAL(12,2) NOT NULL, cost DECIMAL(12,2) NOT NULL, created_at DATETIME NOT NULL, CHECK(price>0), CHECK(cost>=0 AND cost<price));
CREATE TABLE orders (order_id BIGINT PRIMARY KEY, user_id BIGINT NOT NULL, order_time DATETIME NOT NULL, order_status ENUM('created','paid','completed','cancelled','refunded') NOT NULL, total_amount DECIMAL(12,2) NOT NULL, discount_amount DECIMAL(12,2) NOT NULL DEFAULT 0, shipping_amount DECIMAL(12,2) NOT NULL DEFAULT 0, CONSTRAINT fk_orders_user FOREIGN KEY(user_id) REFERENCES users(user_id), CHECK(total_amount>=0), CHECK(discount_amount>=0), CHECK(shipping_amount>=0));
CREATE TABLE order_items (order_item_id BIGINT PRIMARY KEY, order_id BIGINT NOT NULL, product_id BIGINT NOT NULL, quantity INT NOT NULL, unit_price DECIMAL(12,2) NOT NULL, discount DECIMAL(12,2) NOT NULL DEFAULT 0, CONSTRAINT fk_items_order FOREIGN KEY(order_id) REFERENCES orders(order_id), CONSTRAINT fk_items_product FOREIGN KEY(product_id) REFERENCES products(product_id), CHECK(quantity>0), CHECK(unit_price>0), CHECK(discount>=0));
CREATE TABLE payments (payment_id BIGINT PRIMARY KEY, order_id BIGINT NOT NULL UNIQUE, payment_time DATETIME NOT NULL, payment_method ENUM('alipay','wechat','card') NOT NULL, payment_amount DECIMAL(12,2) NOT NULL, payment_status ENUM('success','failed','refunded') NOT NULL, CONSTRAINT fk_payment_order FOREIGN KEY(order_id) REFERENCES orders(order_id), CHECK(payment_amount>=0));
CREATE TABLE user_events (event_id BIGINT PRIMARY KEY, user_id BIGINT NOT NULL, event_time DATETIME NOT NULL, event_type ENUM('register','login','view','favorite','add_to_cart','purchase','payment') NOT NULL, product_id BIGINT NULL, session_id VARCHAR(64) NOT NULL, device ENUM('Android','iOS','Web') NOT NULL, CONSTRAINT fk_events_user FOREIGN KEY(user_id) REFERENCES users(user_id), CONSTRAINT fk_events_product FOREIGN KEY(product_id) REFERENCES products(product_id));

